// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/home.proto

package org.bartos.core.protobuf;

/**
 * Protobuf type {@code home.HomeDTO}
 */
public final class HomeDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:home.HomeDTO)
    HomeDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HomeDTO.newBuilder() to construct.
  private HomeDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HomeDTO() {
    id_ = "";
    name_ = "";
    room_ = java.util.Collections.emptyList();
    users_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    devices_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    invitations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HomeDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HomeDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              room_ = new java.util.ArrayList<org.bartos.core.protobuf.RoomDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            room_.add(
                input.readMessage(org.bartos.core.protobuf.RoomDTO.parser(), extensionRegistry));
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              users_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            users_.add(s);
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              devices_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            devices_.add(s);
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              invitations_ = new java.util.ArrayList<org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO>();
              mutable_bitField0_ |= 0x00000008;
            }
            invitations_.add(
                input.readMessage(org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        room_ = java.util.Collections.unmodifiableList(room_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        users_ = users_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        devices_ = devices_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        invitations_ = java.util.Collections.unmodifiableList(invitations_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.bartos.core.protobuf.HomeDTO.class, org.bartos.core.protobuf.HomeDTO.Builder.class);
  }

  public interface HomeInvitationDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:home.HomeDTO.HomeInvitationDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string issuer = 2;</code>
     * @return The issuer.
     */
    java.lang.String getIssuer();
    /**
     * <code>string issuer = 2;</code>
     * @return The bytes for issuer.
     */
    com.google.protobuf.ByteString
        getIssuerBytes();

    /**
     * <code>string receiver = 3;</code>
     * @return The receiver.
     */
    java.lang.String getReceiver();
    /**
     * <code>string receiver = 3;</code>
     * @return The bytes for receiver.
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>.home.HomeDTO home = 4;</code>
     * @return Whether the home field is set.
     */
    boolean hasHome();
    /**
     * <code>.home.HomeDTO home = 4;</code>
     * @return The home.
     */
    org.bartos.core.protobuf.HomeDTO getHome();
    /**
     * <code>.home.HomeDTO home = 4;</code>
     */
    org.bartos.core.protobuf.HomeDTOOrBuilder getHomeOrBuilder();
  }
  /**
   * Protobuf type {@code home.HomeDTO.HomeInvitationDTO}
   */
  public static final class HomeInvitationDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:home.HomeDTO.HomeInvitationDTO)
      HomeInvitationDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HomeInvitationDTO.newBuilder() to construct.
    private HomeInvitationDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HomeInvitationDTO() {
      id_ = "";
      issuer_ = "";
      receiver_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HomeInvitationDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HomeInvitationDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              issuer_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 34: {
              org.bartos.core.protobuf.HomeDTO.Builder subBuilder = null;
              if (home_ != null) {
                subBuilder = home_.toBuilder();
              }
              home_ = input.readMessage(org.bartos.core.protobuf.HomeDTO.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(home_);
                home_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_HomeInvitationDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_HomeInvitationDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.class, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSUER_FIELD_NUMBER = 2;
    private volatile java.lang.Object issuer_;
    /**
     * <code>string issuer = 2;</code>
     * @return The issuer.
     */
    @java.lang.Override
    public java.lang.String getIssuer() {
      java.lang.Object ref = issuer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        issuer_ = s;
        return s;
      }
    }
    /**
     * <code>string issuer = 2;</code>
     * @return The bytes for issuer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIssuerBytes() {
      java.lang.Object ref = issuer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        issuer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 3;
    private volatile java.lang.Object receiver_;
    /**
     * <code>string receiver = 3;</code>
     * @return The receiver.
     */
    @java.lang.Override
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>string receiver = 3;</code>
     * @return The bytes for receiver.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOME_FIELD_NUMBER = 4;
    private org.bartos.core.protobuf.HomeDTO home_;
    /**
     * <code>.home.HomeDTO home = 4;</code>
     * @return Whether the home field is set.
     */
    @java.lang.Override
    public boolean hasHome() {
      return home_ != null;
    }
    /**
     * <code>.home.HomeDTO home = 4;</code>
     * @return The home.
     */
    @java.lang.Override
    public org.bartos.core.protobuf.HomeDTO getHome() {
      return home_ == null ? org.bartos.core.protobuf.HomeDTO.getDefaultInstance() : home_;
    }
    /**
     * <code>.home.HomeDTO home = 4;</code>
     */
    @java.lang.Override
    public org.bartos.core.protobuf.HomeDTOOrBuilder getHomeOrBuilder() {
      return getHome();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getIssuerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, issuer_);
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiver_);
      }
      if (home_ != null) {
        output.writeMessage(4, getHome());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getIssuerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, issuer_);
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, receiver_);
      }
      if (home_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getHome());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO)) {
        return super.equals(obj);
      }
      org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO other = (org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getIssuer()
          .equals(other.getIssuer())) return false;
      if (!getReceiver()
          .equals(other.getReceiver())) return false;
      if (hasHome() != other.hasHome()) return false;
      if (hasHome()) {
        if (!getHome()
            .equals(other.getHome())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + ISSUER_FIELD_NUMBER;
      hash = (53 * hash) + getIssuer().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      if (hasHome()) {
        hash = (37 * hash) + HOME_FIELD_NUMBER;
        hash = (53 * hash) + getHome().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code home.HomeDTO.HomeInvitationDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:home.HomeDTO.HomeInvitationDTO)
        org.bartos.core.protobuf.HomeDTO.HomeInvitationDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_HomeInvitationDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_HomeInvitationDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.class, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder.class);
      }

      // Construct using org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        issuer_ = "";

        receiver_ = "";

        if (homeBuilder_ == null) {
          home_ = null;
        } else {
          home_ = null;
          homeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_HomeInvitationDTO_descriptor;
      }

      @java.lang.Override
      public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO getDefaultInstanceForType() {
        return org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.getDefaultInstance();
      }

      @java.lang.Override
      public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO build() {
        org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO buildPartial() {
        org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO result = new org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO(this);
        result.id_ = id_;
        result.issuer_ = issuer_;
        result.receiver_ = receiver_;
        if (homeBuilder_ == null) {
          result.home_ = home_;
        } else {
          result.home_ = homeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO) {
          return mergeFrom((org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO other) {
        if (other == org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getIssuer().isEmpty()) {
          issuer_ = other.issuer_;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.hasHome()) {
          mergeHome(other.getHome());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object issuer_ = "";
      /**
       * <code>string issuer = 2;</code>
       * @return The issuer.
       */
      public java.lang.String getIssuer() {
        java.lang.Object ref = issuer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          issuer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string issuer = 2;</code>
       * @return The bytes for issuer.
       */
      public com.google.protobuf.ByteString
          getIssuerBytes() {
        java.lang.Object ref = issuer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          issuer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string issuer = 2;</code>
       * @param value The issuer to set.
       * @return This builder for chaining.
       */
      public Builder setIssuer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        issuer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string issuer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIssuer() {
        
        issuer_ = getDefaultInstance().getIssuer();
        onChanged();
        return this;
      }
      /**
       * <code>string issuer = 2;</code>
       * @param value The bytes for issuer to set.
       * @return This builder for chaining.
       */
      public Builder setIssuerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        issuer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>string receiver = 3;</code>
       * @return The receiver.
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiver = 3;</code>
       * @return The bytes for receiver.
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiver = 3;</code>
       * @param value The receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 3;</code>
       * @param value The bytes for receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private org.bartos.core.protobuf.HomeDTO home_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.bartos.core.protobuf.HomeDTO, org.bartos.core.protobuf.HomeDTO.Builder, org.bartos.core.protobuf.HomeDTOOrBuilder> homeBuilder_;
      /**
       * <code>.home.HomeDTO home = 4;</code>
       * @return Whether the home field is set.
       */
      public boolean hasHome() {
        return homeBuilder_ != null || home_ != null;
      }
      /**
       * <code>.home.HomeDTO home = 4;</code>
       * @return The home.
       */
      public org.bartos.core.protobuf.HomeDTO getHome() {
        if (homeBuilder_ == null) {
          return home_ == null ? org.bartos.core.protobuf.HomeDTO.getDefaultInstance() : home_;
        } else {
          return homeBuilder_.getMessage();
        }
      }
      /**
       * <code>.home.HomeDTO home = 4;</code>
       */
      public Builder setHome(org.bartos.core.protobuf.HomeDTO value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          home_ = value;
          onChanged();
        } else {
          homeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.home.HomeDTO home = 4;</code>
       */
      public Builder setHome(
          org.bartos.core.protobuf.HomeDTO.Builder builderForValue) {
        if (homeBuilder_ == null) {
          home_ = builderForValue.build();
          onChanged();
        } else {
          homeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.home.HomeDTO home = 4;</code>
       */
      public Builder mergeHome(org.bartos.core.protobuf.HomeDTO value) {
        if (homeBuilder_ == null) {
          if (home_ != null) {
            home_ =
              org.bartos.core.protobuf.HomeDTO.newBuilder(home_).mergeFrom(value).buildPartial();
          } else {
            home_ = value;
          }
          onChanged();
        } else {
          homeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.home.HomeDTO home = 4;</code>
       */
      public Builder clearHome() {
        if (homeBuilder_ == null) {
          home_ = null;
          onChanged();
        } else {
          home_ = null;
          homeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.home.HomeDTO home = 4;</code>
       */
      public org.bartos.core.protobuf.HomeDTO.Builder getHomeBuilder() {
        
        onChanged();
        return getHomeFieldBuilder().getBuilder();
      }
      /**
       * <code>.home.HomeDTO home = 4;</code>
       */
      public org.bartos.core.protobuf.HomeDTOOrBuilder getHomeOrBuilder() {
        if (homeBuilder_ != null) {
          return homeBuilder_.getMessageOrBuilder();
        } else {
          return home_ == null ?
              org.bartos.core.protobuf.HomeDTO.getDefaultInstance() : home_;
        }
      }
      /**
       * <code>.home.HomeDTO home = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.bartos.core.protobuf.HomeDTO, org.bartos.core.protobuf.HomeDTO.Builder, org.bartos.core.protobuf.HomeDTOOrBuilder> 
          getHomeFieldBuilder() {
        if (homeBuilder_ == null) {
          homeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.bartos.core.protobuf.HomeDTO, org.bartos.core.protobuf.HomeDTO.Builder, org.bartos.core.protobuf.HomeDTOOrBuilder>(
                  getHome(),
                  getParentForChildren(),
                  isClean());
          home_ = null;
        }
        return homeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:home.HomeDTO.HomeInvitationDTO)
    }

    // @@protoc_insertion_point(class_scope:home.HomeDTO.HomeInvitationDTO)
    private static final org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO();
    }

    public static org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HomeInvitationDTO>
        PARSER = new com.google.protobuf.AbstractParser<HomeInvitationDTO>() {
      @java.lang.Override
      public HomeInvitationDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HomeInvitationDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HomeInvitationDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HomeInvitationDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_FIELD_NUMBER = 3;
  private java.util.List<org.bartos.core.protobuf.RoomDTO> room_;
  /**
   * <code>repeated .home.RoomDTO room = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.bartos.core.protobuf.RoomDTO> getRoomList() {
    return room_;
  }
  /**
   * <code>repeated .home.RoomDTO room = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.bartos.core.protobuf.RoomDTOOrBuilder> 
      getRoomOrBuilderList() {
    return room_;
  }
  /**
   * <code>repeated .home.RoomDTO room = 3;</code>
   */
  @java.lang.Override
  public int getRoomCount() {
    return room_.size();
  }
  /**
   * <code>repeated .home.RoomDTO room = 3;</code>
   */
  @java.lang.Override
  public org.bartos.core.protobuf.RoomDTO getRoom(int index) {
    return room_.get(index);
  }
  /**
   * <code>repeated .home.RoomDTO room = 3;</code>
   */
  @java.lang.Override
  public org.bartos.core.protobuf.RoomDTOOrBuilder getRoomOrBuilder(
      int index) {
    return room_.get(index);
  }

  public static final int USERS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList users_;
  /**
   * <code>repeated string users = 4;</code>
   * @return A list containing the users.
   */
  public com.google.protobuf.ProtocolStringList
      getUsersList() {
    return users_;
  }
  /**
   * <code>repeated string users = 4;</code>
   * @return The count of users.
   */
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated string users = 4;</code>
   * @param index The index of the element to return.
   * @return The users at the given index.
   */
  public java.lang.String getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated string users = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the users at the given index.
   */
  public com.google.protobuf.ByteString
      getUsersBytes(int index) {
    return users_.getByteString(index);
  }

  public static final int DEVICES_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList devices_;
  /**
   * <code>repeated string devices = 5;</code>
   * @return A list containing the devices.
   */
  public com.google.protobuf.ProtocolStringList
      getDevicesList() {
    return devices_;
  }
  /**
   * <code>repeated string devices = 5;</code>
   * @return The count of devices.
   */
  public int getDevicesCount() {
    return devices_.size();
  }
  /**
   * <code>repeated string devices = 5;</code>
   * @param index The index of the element to return.
   * @return The devices at the given index.
   */
  public java.lang.String getDevices(int index) {
    return devices_.get(index);
  }
  /**
   * <code>repeated string devices = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the devices at the given index.
   */
  public com.google.protobuf.ByteString
      getDevicesBytes(int index) {
    return devices_.getByteString(index);
  }

  public static final int INVITATIONS_FIELD_NUMBER = 6;
  private java.util.List<org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO> invitations_;
  /**
   * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
   */
  @java.lang.Override
  public java.util.List<org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO> getInvitationsList() {
    return invitations_;
  }
  /**
   * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.bartos.core.protobuf.HomeDTO.HomeInvitationDTOOrBuilder> 
      getInvitationsOrBuilderList() {
    return invitations_;
  }
  /**
   * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
   */
  @java.lang.Override
  public int getInvitationsCount() {
    return invitations_.size();
  }
  /**
   * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
   */
  @java.lang.Override
  public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO getInvitations(int index) {
    return invitations_.get(index);
  }
  /**
   * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
   */
  @java.lang.Override
  public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTOOrBuilder getInvitationsOrBuilder(
      int index) {
    return invitations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    for (int i = 0; i < room_.size(); i++) {
      output.writeMessage(3, room_.get(i));
    }
    for (int i = 0; i < users_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, users_.getRaw(i));
    }
    for (int i = 0; i < devices_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, devices_.getRaw(i));
    }
    for (int i = 0; i < invitations_.size(); i++) {
      output.writeMessage(6, invitations_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    for (int i = 0; i < room_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, room_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < users_.size(); i++) {
        dataSize += computeStringSizeNoTag(users_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUsersList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < devices_.size(); i++) {
        dataSize += computeStringSizeNoTag(devices_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDevicesList().size();
    }
    for (int i = 0; i < invitations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, invitations_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.bartos.core.protobuf.HomeDTO)) {
      return super.equals(obj);
    }
    org.bartos.core.protobuf.HomeDTO other = (org.bartos.core.protobuf.HomeDTO) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getRoomList()
        .equals(other.getRoomList())) return false;
    if (!getUsersList()
        .equals(other.getUsersList())) return false;
    if (!getDevicesList()
        .equals(other.getDevicesList())) return false;
    if (!getInvitationsList()
        .equals(other.getInvitationsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getRoomCount() > 0) {
      hash = (37 * hash) + ROOM_FIELD_NUMBER;
      hash = (53 * hash) + getRoomList().hashCode();
    }
    if (getUsersCount() > 0) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsersList().hashCode();
    }
    if (getDevicesCount() > 0) {
      hash = (37 * hash) + DEVICES_FIELD_NUMBER;
      hash = (53 * hash) + getDevicesList().hashCode();
    }
    if (getInvitationsCount() > 0) {
      hash = (37 * hash) + INVITATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getInvitationsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.bartos.core.protobuf.HomeDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bartos.core.protobuf.HomeDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.bartos.core.protobuf.HomeDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bartos.core.protobuf.HomeDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.bartos.core.protobuf.HomeDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code home.HomeDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:home.HomeDTO)
      org.bartos.core.protobuf.HomeDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bartos.core.protobuf.HomeDTO.class, org.bartos.core.protobuf.HomeDTO.Builder.class);
    }

    // Construct using org.bartos.core.protobuf.HomeDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRoomFieldBuilder();
        getInvitationsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      if (roomBuilder_ == null) {
        room_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        roomBuilder_.clear();
      }
      users_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      devices_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (invitationsBuilder_ == null) {
        invitations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        invitationsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.bartos.core.protobuf.HomeProto.internal_static_home_HomeDTO_descriptor;
    }

    @java.lang.Override
    public org.bartos.core.protobuf.HomeDTO getDefaultInstanceForType() {
      return org.bartos.core.protobuf.HomeDTO.getDefaultInstance();
    }

    @java.lang.Override
    public org.bartos.core.protobuf.HomeDTO build() {
      org.bartos.core.protobuf.HomeDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.bartos.core.protobuf.HomeDTO buildPartial() {
      org.bartos.core.protobuf.HomeDTO result = new org.bartos.core.protobuf.HomeDTO(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.name_ = name_;
      if (roomBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          room_ = java.util.Collections.unmodifiableList(room_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.room_ = room_;
      } else {
        result.room_ = roomBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        users_ = users_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.users_ = users_;
      if (((bitField0_ & 0x00000004) != 0)) {
        devices_ = devices_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.devices_ = devices_;
      if (invitationsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          invitations_ = java.util.Collections.unmodifiableList(invitations_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.invitations_ = invitations_;
      } else {
        result.invitations_ = invitationsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.bartos.core.protobuf.HomeDTO) {
        return mergeFrom((org.bartos.core.protobuf.HomeDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.bartos.core.protobuf.HomeDTO other) {
      if (other == org.bartos.core.protobuf.HomeDTO.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (roomBuilder_ == null) {
        if (!other.room_.isEmpty()) {
          if (room_.isEmpty()) {
            room_ = other.room_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRoomIsMutable();
            room_.addAll(other.room_);
          }
          onChanged();
        }
      } else {
        if (!other.room_.isEmpty()) {
          if (roomBuilder_.isEmpty()) {
            roomBuilder_.dispose();
            roomBuilder_ = null;
            room_ = other.room_;
            bitField0_ = (bitField0_ & ~0x00000001);
            roomBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRoomFieldBuilder() : null;
          } else {
            roomBuilder_.addAllMessages(other.room_);
          }
        }
      }
      if (!other.users_.isEmpty()) {
        if (users_.isEmpty()) {
          users_ = other.users_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureUsersIsMutable();
          users_.addAll(other.users_);
        }
        onChanged();
      }
      if (!other.devices_.isEmpty()) {
        if (devices_.isEmpty()) {
          devices_ = other.devices_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDevicesIsMutable();
          devices_.addAll(other.devices_);
        }
        onChanged();
      }
      if (invitationsBuilder_ == null) {
        if (!other.invitations_.isEmpty()) {
          if (invitations_.isEmpty()) {
            invitations_ = other.invitations_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureInvitationsIsMutable();
            invitations_.addAll(other.invitations_);
          }
          onChanged();
        }
      } else {
        if (!other.invitations_.isEmpty()) {
          if (invitationsBuilder_.isEmpty()) {
            invitationsBuilder_.dispose();
            invitationsBuilder_ = null;
            invitations_ = other.invitations_;
            bitField0_ = (bitField0_ & ~0x00000008);
            invitationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvitationsFieldBuilder() : null;
          } else {
            invitationsBuilder_.addAllMessages(other.invitations_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.bartos.core.protobuf.HomeDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.bartos.core.protobuf.HomeDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.bartos.core.protobuf.RoomDTO> room_ =
      java.util.Collections.emptyList();
    private void ensureRoomIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        room_ = new java.util.ArrayList<org.bartos.core.protobuf.RoomDTO>(room_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.bartos.core.protobuf.RoomDTO, org.bartos.core.protobuf.RoomDTO.Builder, org.bartos.core.protobuf.RoomDTOOrBuilder> roomBuilder_;

    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public java.util.List<org.bartos.core.protobuf.RoomDTO> getRoomList() {
      if (roomBuilder_ == null) {
        return java.util.Collections.unmodifiableList(room_);
      } else {
        return roomBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public int getRoomCount() {
      if (roomBuilder_ == null) {
        return room_.size();
      } else {
        return roomBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public org.bartos.core.protobuf.RoomDTO getRoom(int index) {
      if (roomBuilder_ == null) {
        return room_.get(index);
      } else {
        return roomBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder setRoom(
        int index, org.bartos.core.protobuf.RoomDTO value) {
      if (roomBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomIsMutable();
        room_.set(index, value);
        onChanged();
      } else {
        roomBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder setRoom(
        int index, org.bartos.core.protobuf.RoomDTO.Builder builderForValue) {
      if (roomBuilder_ == null) {
        ensureRoomIsMutable();
        room_.set(index, builderForValue.build());
        onChanged();
      } else {
        roomBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder addRoom(org.bartos.core.protobuf.RoomDTO value) {
      if (roomBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomIsMutable();
        room_.add(value);
        onChanged();
      } else {
        roomBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder addRoom(
        int index, org.bartos.core.protobuf.RoomDTO value) {
      if (roomBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomIsMutable();
        room_.add(index, value);
        onChanged();
      } else {
        roomBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder addRoom(
        org.bartos.core.protobuf.RoomDTO.Builder builderForValue) {
      if (roomBuilder_ == null) {
        ensureRoomIsMutable();
        room_.add(builderForValue.build());
        onChanged();
      } else {
        roomBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder addRoom(
        int index, org.bartos.core.protobuf.RoomDTO.Builder builderForValue) {
      if (roomBuilder_ == null) {
        ensureRoomIsMutable();
        room_.add(index, builderForValue.build());
        onChanged();
      } else {
        roomBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder addAllRoom(
        java.lang.Iterable<? extends org.bartos.core.protobuf.RoomDTO> values) {
      if (roomBuilder_ == null) {
        ensureRoomIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, room_);
        onChanged();
      } else {
        roomBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder clearRoom() {
      if (roomBuilder_ == null) {
        room_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        roomBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public Builder removeRoom(int index) {
      if (roomBuilder_ == null) {
        ensureRoomIsMutable();
        room_.remove(index);
        onChanged();
      } else {
        roomBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public org.bartos.core.protobuf.RoomDTO.Builder getRoomBuilder(
        int index) {
      return getRoomFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public org.bartos.core.protobuf.RoomDTOOrBuilder getRoomOrBuilder(
        int index) {
      if (roomBuilder_ == null) {
        return room_.get(index);  } else {
        return roomBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public java.util.List<? extends org.bartos.core.protobuf.RoomDTOOrBuilder> 
         getRoomOrBuilderList() {
      if (roomBuilder_ != null) {
        return roomBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(room_);
      }
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public org.bartos.core.protobuf.RoomDTO.Builder addRoomBuilder() {
      return getRoomFieldBuilder().addBuilder(
          org.bartos.core.protobuf.RoomDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public org.bartos.core.protobuf.RoomDTO.Builder addRoomBuilder(
        int index) {
      return getRoomFieldBuilder().addBuilder(
          index, org.bartos.core.protobuf.RoomDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .home.RoomDTO room = 3;</code>
     */
    public java.util.List<org.bartos.core.protobuf.RoomDTO.Builder> 
         getRoomBuilderList() {
      return getRoomFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.bartos.core.protobuf.RoomDTO, org.bartos.core.protobuf.RoomDTO.Builder, org.bartos.core.protobuf.RoomDTOOrBuilder> 
        getRoomFieldBuilder() {
      if (roomBuilder_ == null) {
        roomBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.bartos.core.protobuf.RoomDTO, org.bartos.core.protobuf.RoomDTO.Builder, org.bartos.core.protobuf.RoomDTOOrBuilder>(
                room_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        room_ = null;
      }
      return roomBuilder_;
    }

    private com.google.protobuf.LazyStringList users_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureUsersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        users_ = new com.google.protobuf.LazyStringArrayList(users_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string users = 4;</code>
     * @return A list containing the users.
     */
    public com.google.protobuf.ProtocolStringList
        getUsersList() {
      return users_.getUnmodifiableView();
    }
    /**
     * <code>repeated string users = 4;</code>
     * @return The count of users.
     */
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated string users = 4;</code>
     * @param index The index of the element to return.
     * @return The users at the given index.
     */
    public java.lang.String getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated string users = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the users at the given index.
     */
    public com.google.protobuf.ByteString
        getUsersBytes(int index) {
      return users_.getByteString(index);
    }
    /**
     * <code>repeated string users = 4;</code>
     * @param index The index to set the value at.
     * @param value The users to set.
     * @return This builder for chaining.
     */
    public Builder setUsers(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUsersIsMutable();
      users_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string users = 4;</code>
     * @param value The users to add.
     * @return This builder for chaining.
     */
    public Builder addUsers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUsersIsMutable();
      users_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string users = 4;</code>
     * @param values The users to add.
     * @return This builder for chaining.
     */
    public Builder addAllUsers(
        java.lang.Iterable<java.lang.String> values) {
      ensureUsersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, users_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string users = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsers() {
      users_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string users = 4;</code>
     * @param value The bytes of the users to add.
     * @return This builder for chaining.
     */
    public Builder addUsersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUsersIsMutable();
      users_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList devices_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDevicesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        devices_ = new com.google.protobuf.LazyStringArrayList(devices_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @return A list containing the devices.
     */
    public com.google.protobuf.ProtocolStringList
        getDevicesList() {
      return devices_.getUnmodifiableView();
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @return The count of devices.
     */
    public int getDevicesCount() {
      return devices_.size();
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @param index The index of the element to return.
     * @return The devices at the given index.
     */
    public java.lang.String getDevices(int index) {
      return devices_.get(index);
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the devices at the given index.
     */
    public com.google.protobuf.ByteString
        getDevicesBytes(int index) {
      return devices_.getByteString(index);
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @param index The index to set the value at.
     * @param value The devices to set.
     * @return This builder for chaining.
     */
    public Builder setDevices(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDevicesIsMutable();
      devices_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @param value The devices to add.
     * @return This builder for chaining.
     */
    public Builder addDevices(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDevicesIsMutable();
      devices_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @param values The devices to add.
     * @return This builder for chaining.
     */
    public Builder addAllDevices(
        java.lang.Iterable<java.lang.String> values) {
      ensureDevicesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, devices_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDevices() {
      devices_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string devices = 5;</code>
     * @param value The bytes of the devices to add.
     * @return This builder for chaining.
     */
    public Builder addDevicesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDevicesIsMutable();
      devices_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO> invitations_ =
      java.util.Collections.emptyList();
    private void ensureInvitationsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        invitations_ = new java.util.ArrayList<org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO>(invitations_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTOOrBuilder> invitationsBuilder_;

    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public java.util.List<org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO> getInvitationsList() {
      if (invitationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invitations_);
      } else {
        return invitationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public int getInvitationsCount() {
      if (invitationsBuilder_ == null) {
        return invitations_.size();
      } else {
        return invitationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO getInvitations(int index) {
      if (invitationsBuilder_ == null) {
        return invitations_.get(index);
      } else {
        return invitationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder setInvitations(
        int index, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO value) {
      if (invitationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitationsIsMutable();
        invitations_.set(index, value);
        onChanged();
      } else {
        invitationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder setInvitations(
        int index, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder builderForValue) {
      if (invitationsBuilder_ == null) {
        ensureInvitationsIsMutable();
        invitations_.set(index, builderForValue.build());
        onChanged();
      } else {
        invitationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder addInvitations(org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO value) {
      if (invitationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitationsIsMutable();
        invitations_.add(value);
        onChanged();
      } else {
        invitationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder addInvitations(
        int index, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO value) {
      if (invitationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitationsIsMutable();
        invitations_.add(index, value);
        onChanged();
      } else {
        invitationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder addInvitations(
        org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder builderForValue) {
      if (invitationsBuilder_ == null) {
        ensureInvitationsIsMutable();
        invitations_.add(builderForValue.build());
        onChanged();
      } else {
        invitationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder addInvitations(
        int index, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder builderForValue) {
      if (invitationsBuilder_ == null) {
        ensureInvitationsIsMutable();
        invitations_.add(index, builderForValue.build());
        onChanged();
      } else {
        invitationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder addAllInvitations(
        java.lang.Iterable<? extends org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO> values) {
      if (invitationsBuilder_ == null) {
        ensureInvitationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invitations_);
        onChanged();
      } else {
        invitationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder clearInvitations() {
      if (invitationsBuilder_ == null) {
        invitations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        invitationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public Builder removeInvitations(int index) {
      if (invitationsBuilder_ == null) {
        ensureInvitationsIsMutable();
        invitations_.remove(index);
        onChanged();
      } else {
        invitationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder getInvitationsBuilder(
        int index) {
      return getInvitationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTOOrBuilder getInvitationsOrBuilder(
        int index) {
      if (invitationsBuilder_ == null) {
        return invitations_.get(index);  } else {
        return invitationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public java.util.List<? extends org.bartos.core.protobuf.HomeDTO.HomeInvitationDTOOrBuilder> 
         getInvitationsOrBuilderList() {
      if (invitationsBuilder_ != null) {
        return invitationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invitations_);
      }
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder addInvitationsBuilder() {
      return getInvitationsFieldBuilder().addBuilder(
          org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder addInvitationsBuilder(
        int index) {
      return getInvitationsFieldBuilder().addBuilder(
          index, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .home.HomeDTO.HomeInvitationDTO invitations = 6;</code>
     */
    public java.util.List<org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder> 
         getInvitationsBuilderList() {
      return getInvitationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTOOrBuilder> 
        getInvitationsFieldBuilder() {
      if (invitationsBuilder_ == null) {
        invitationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTO.Builder, org.bartos.core.protobuf.HomeDTO.HomeInvitationDTOOrBuilder>(
                invitations_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        invitations_ = null;
      }
      return invitationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:home.HomeDTO)
  }

  // @@protoc_insertion_point(class_scope:home.HomeDTO)
  private static final org.bartos.core.protobuf.HomeDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.bartos.core.protobuf.HomeDTO();
  }

  public static org.bartos.core.protobuf.HomeDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HomeDTO>
      PARSER = new com.google.protobuf.AbstractParser<HomeDTO>() {
    @java.lang.Override
    public HomeDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HomeDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HomeDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HomeDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.bartos.core.protobuf.HomeDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

