// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/home.proto

package org.bartos.core.protobuf;

public final class HomeProto {
  private HomeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_home_HomeDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_home_HomeDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_home_HomeDTO_HomeInvitationDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_home_HomeDTO_HomeInvitationDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_home_RoomDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_home_RoomDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PATH/home.proto\022\004home\"\366\001\n\007HomeDTO\022\n\n\002i" +
      "d\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\033\n\004room\030\003 \003(\0132\r.ho" +
      "me.RoomDTO\022\r\n\005users\030\004 \003(\t\022\017\n\007devices\030\005 \003" +
      "(\t\0224\n\013invitations\030\006 \003(\0132\037.home.HomeDTO.H" +
      "omeInvitationDTO\032^\n\021HomeInvitationDTO\022\n\n" +
      "\002id\030\001 \001(\t\022\016\n\006issuer\030\002 \001(\t\022\020\n\010receiver\030\003 " +
      "\001(\t\022\033\n\004home\030\004 \001(\0132\r.home.HomeDTO\"\321\001\n\007Roo" +
      "mDTO\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022$\n\004type\030\003" +
      " \001(\0162\026.home.RoomDTO.RoomType\022\017\n\007home_id\030" +
      "\004 \001(\t\022\017\n\007devices\030\005 \003(\t\"d\n\010RoomType\022\010\n\004NO" +
      "NE\020\000\022\013\n\007KITCHEN\020\001\022\013\n\007BEDROOM\020\002\022\014\n\010BATHRO" +
      "OM\020\003\022\017\n\013LIVING_ROOM\020\004\022\n\n\006GARAGE\020\005\022\t\n\005OTH" +
      "ER\020\006B)\n\030org.bartos.core.protobufB\tHomePr" +
      "otoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_home_HomeDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_home_HomeDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_home_HomeDTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Room", "Users", "Devices", "Invitations", });
    internal_static_home_HomeDTO_HomeInvitationDTO_descriptor =
      internal_static_home_HomeDTO_descriptor.getNestedTypes().get(0);
    internal_static_home_HomeDTO_HomeInvitationDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_home_HomeDTO_HomeInvitationDTO_descriptor,
        new java.lang.String[] { "Id", "Issuer", "Receiver", "Home", });
    internal_static_home_RoomDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_home_RoomDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_home_RoomDTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Type", "HomeId", "Devices", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
