// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/home.proto

package org.bartos.core.protobuf;

public interface RoomDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:home.RoomDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.home.RoomDTO.RoomType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.home.RoomDTO.RoomType type = 3;</code>
   * @return The type.
   */
  org.bartos.core.protobuf.RoomDTO.RoomType getType();

  /**
   * <code>string home_id = 4;</code>
   * @return The homeId.
   */
  java.lang.String getHomeId();
  /**
   * <code>string home_id = 4;</code>
   * @return The bytes for homeId.
   */
  com.google.protobuf.ByteString
      getHomeIdBytes();

  /**
   * <code>repeated string devices = 5;</code>
   * @return A list containing the devices.
   */
  java.util.List<java.lang.String>
      getDevicesList();
  /**
   * <code>repeated string devices = 5;</code>
   * @return The count of devices.
   */
  int getDevicesCount();
  /**
   * <code>repeated string devices = 5;</code>
   * @param index The index of the element to return.
   * @return The devices at the given index.
   */
  java.lang.String getDevices(int index);
  /**
   * <code>repeated string devices = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the devices at the given index.
   */
  com.google.protobuf.ByteString
      getDevicesBytes(int index);
}
